### ISSUE TITLE
'repeat multiple times'

### ISSUE THREAD

**Issue by mkohlhaas** [SquareBracketAssociates/Booklet-uFFI#47]
`This version will run on all three platform types, and do so without us having
to repeat the same code multiple times.`

`repeat multiple times` is not a proper expression.

Proposal:

`This version will run on all three platform without repetitive code.`

**Comment by mkohlhaas** [comment]
Hi Torsten,

files are in Windows text format. I only have Linux boxes. What would you advice I should do?

**Comment by mkohlhaas** [comment]
Okay. Kate seems to handle the files properly. Just tell me which changes I should make. Then I'll do it.

**Comment by astares** [comment]
@mkohlhaas You can just hit the "." (dot) key in the browser in github to get visualstudio code and edit. When you commit you might switch to an own fork and create a PR with it.
